steps:
  test:
    image: rust
    commands:
      - .woodpecker/install_cargo_hack.sh
      - cargo-hack \
        --each-feature \
        --exclude-no-default-features \
        --exclude-all-features \
        test
      - cargo doc --no-deps --document-private-items
  msrv:
    image: rust:1.72
    commands:
      - .woodpecker/install_cargo_hack.sh
      - cargo-hack \
        --each-feature \
        --exclude-no-default-features \
        --exclude-all-features \
        check
      - cargo-hack \
        --each-feature \
        --exclude-no-default-features \
        --exclude-all-features \
        test
