[package]
name = "close_already"
description = "Speeds up programs handling lots of files on Windows"
categories = ["filesystem", "concurrency"]
keywords = ["windows", "fs", "file", "files", "handle"]
version = "0.2.1"
edition = "2021"
rust-version = "1.72"
authors = ["alpha-tango-kilo <git@heyatk.com>"]
license = "MIT OR Apache-2.0"
repository = "https://codeberg.org/alpha-tango-kilo/close_already"

[features]
default = ["backend-threadpool"]
backend-rayon = ["rayon"]
backend-threadpool = ["threadpool"]

[dependencies]
mutually_exclusive_features = "0.0.3"
# Backends
rayon = { version = "1", optional = true }
threadpool = { version = "1.7", optional = true }

[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"
