[package]
name = "close_already"
description = "Speeds up programs handling lots of files on Windows"
categories = ["filesystem", "concurrency"]
keywords = ["windows", "fs", "file", "files", "handle"]
version = "0.1.0"
edition = "2021"
rust-version = "1.72"
authors = ["alpha-tango-kilo <git@heyatk.com>"]
license = "MIT OR Apache-2.0"
repository = "https://codeberg.org/alpha-tango-kilo/close_already"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
threadpool = "1"
