on:
  pull_request:
  push:

name: Build & test

jobs:
  test:
    name: Test (${{ matrix.os }})
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install cargo-hack
        uses: taiki-e/install-action@cargo-hack
      - name: Run tests on all backends & test documentation
        shell: bash
        run: |
          cargo hack \
            --each-feature \
            --exclude-no-default-features \
            --exclude-all-features \
            test
          cargo doc --no-deps --document-private-items
  msrv:
    name: Check MSRV (${{ matrix.os }})
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.72.1
      - name: Install cargo-hack
        uses: taiki-e/install-action@cargo-hack
      - name: Ensure compilation & passing tests on all backends
        shell: bash
        run: |
          cargo hack \
            --each-feature \
            --exclude-no-default-features \
            --exclude-all-features \
            check
          cargo hack \
            --each-feature \
            --exclude-no-default-features \
            --exclude-all-features \
            test
