on:
  pull_request:
  push:

name: Build & test

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  test:
    name: Test (${{ matrix.os }})
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install cargo-hack
        uses: taiki-e/install-action@cargo-hack
      - name: Run tests on all backends & test documentation
        shell: bash
        run: |
          cargo hack \
            --each-feature \
            --exclude-no-default-features \
            --exclude-all-features \
            test
      - name: Test documentation (including private)
        shell: bash
        run: |
          cargo doc --no-deps --document-private-items
  miri-windows:
    name: Run Miri tests (Windows)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: miri
      - name: Install cargo-hack
        uses: taiki-e/install-action@cargo-hack
      - name: Run Miri tests on all backends
        shell: bash
        env:
          MIRIFLAGS: "-Zmiri-ignore-leaks"
        run: |
          cargo hack \
            --each-feature \
            --skip default,backend-async-std,backend-smol,backend-rayon \
            --exclude-no-default-features \
            --exclude-all-features \
            miri \
            test
  miri-linux:
    name: Run Miri tests (Linux)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: miri
      - name: Install cargo-hack
        uses: taiki-e/install-action@cargo-hack
      - name: Run Miri tests on all backends
        shell: bash
        run: |
          cargo hack \
            --each-feature \
            --skip default \
            --exclude-no-default-features \
            --exclude-all-features \
            miri \
            test
